name: Auto-merge PRs from master to develop

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.base_ref == 'develop' && github.head_ref == 'master'
    steps:
      - name: Auto-approve
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
