name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull joubina/smartmoveback:latest

    - name: Delete Old Docker Container
      run: sudo docker rm -f smartmovecontainer || true

    - name: Run Docker Container
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: sudo docker run -d -p 8080:8080 --name smartmovecontainer 
        -e DATABASE_URL=${{ secrets.DATABASE_URL }} 
        -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} 
        -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} 
        joubina/smartmoveback