name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull joubina/smartmoveback:latest

    - name: Delete Old Docker Container
      run: sudo docker rm -f smartmovecontainer || true

    - name: Run Docker Container
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        sudo docker run -d -p 8080:8080 --name smartmovecontainer 
        -e DATABASE_URL=${{ secrets.DATABASE_URL }} 
        joubina/smartmoveback
