name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull joubina/smartmoveback:latest

    - name: Delete Old docker container
      run: sudo docker rm -f smartmoveback || true

    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name smartmoveback-container joubina/smartmoveback