name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Check Java version
      run: java -version

    - name: Build with Maven
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: mvn clean package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: smartmoveback-jar
        path: target/properties-backend-0.0.1-SNAPSHOT.jar

    - name: Execute JAR File
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "Starting JAR file with DATABASE_URL=$DATABASE_URL"
        java -Dspring.datasource.url=$DATABASE_URL -jar target/properties-backend-0.0.1-SNAPSHOT.jar &
        JAR_PID=$!
        sleep 60
        if ps -p $JAR_PID > /dev/null
        then
           echo "JAR file is still running after 60 seconds, killing process"
           kill $JAR_PID
           exit 0
        else
           echo "JAR file finished within 60 seconds"
        fi

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t joubina/smartmoveback .

    - name: Push to Dockerhub
      run: docker push joubina/smartmoveback:latest

    - name: Show test logs on failure
      if: failure()
      run: cat target/surefire-reports/*.txt