name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: DATABASE_URL="$DATABASE_URL" mvn clean package
      
    - name: Show Maven test results
      run: |
        ls -la target/surefire-reports/
        cat target/surefire-reports/*.txt || true

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: smartmoveback-jar
        path: target/smartmoveback-0.0.1-SNAPSHOT.jar
    
    - name: Check JAR existence
      run: test -f target/smartmoveback-0.0.1-SNAPSHOT.jar || { echo "JAR file not found!"; exit 1; }
      
    - name: Execute JAR File
      run: |
        sudo kill -9 `sudo lsof -t -i:8080` || true
        sudo java -jar target/smartmoveback-0.0.1-SNAPSHOT.jar

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t joubina/smartmoveback .

    - name: Push to Dockerhub
      run: docker push joubina/smartmoveback:latest