name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Check Java version
      run: java -version

    - name: Build with Maven
      env:
        DATABASE_URL: "${{ secrets.DATABASE_URL }}"
      run: mvn clean package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: smartmoveback-jar
        path: target/properties-backend-0.0.1-SNAPSHOT.jar

    - name: Execute JAR File
      run: java -jar target/properties-backend-0.0.1-SNAPSHOT.jar

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t joubina/smartmoveback .

    - name: Push to Dockerhub
      run: docker push joubina/smartmoveback:latest
