name: Build and Test Java Spring Boot Application

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      env:
        DATABASE_URL: ${{secrets.DATABASE_URL}}
      run:  echo "Hola base $DATABASE_URL"

    - name: Build with Maven
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: DATABASE_URL="$DATABASE_URL" mvn clean verify
    - name: Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: SpringBoot Report               # Name of the folder
          path: target/site/serenity/           # Path to test results
